#str() aris sityva brwyalebis garshemo mag:"andria" "machavariani"     int() aris ricxvebi mag: 13 an 17        float() aris migebuli atwiladi romelic migebulia ori gayofis ricxvebisagan mag: 6//3=2.0   8/2=4.0

#monacemta tipi aris mag:integeri floati stringi

# print("10" + "20") amisgan gamova 1020 imitom rom "10" + "20" weria brwyalebshida rac brwyalebshi weria egeni ertdeba radgan 10-sa da 20-s shua + weria da es aris snake_case-i rac ricxvebis an asoebs aertebs ertmanets tu brwyalebshi weria ratqma unda

num1 = "10"

num2 = "20"

print(type(num1))

print(type(num2))

print(int(num1))

print(int(num2))

print(10 + 20)

print(10 - 20)

print(10 / 20)

print(10 // 20)

print(10 * 20)

print(10 ** 20)